export const ACCOUNT_STATUS = {
  LOCKED: 'LOCKED',
  VERIFIED: 'VERIFIED',
  ACTIVE: 'active',
  INACTIVE: 'inactive',
};

export const ACCOUNT_ACTIONS = {
  RESEND: 'RESEND',
  LOCK: 'LOCK',
  UNLOCK: 'UNLOCK',
  DELETE: 'DELETE',
  SET_TIME: 'SET_TIME',
  UPDATE_PASSWORD: 'UPDATE_PASSWORD',
  CONFIG_ACCESS_DATA: 'CONFIG_ACCESS_DATA',
};
