export const USER = {
  id: 45,
  username: 'stp.admin',
  email: 'stp.admin@gmail.com',
  phone_number: '0389303982',
  first_name: 'Admin',
  last_name: 'admin',
  avatar_url:
    'https://cdn.senvangdata.com/senvang/2022/12/16/screen-shot-20221207-at-094321.png',
  status: 'active',
  organization_id: 1,
};

export const REQUEST_PROFILE = {
  id: 1,
  full_name: 'Lê Văn A',
  other_name: 'Lê Văn A',
  gender: 'male',
  date_of_birth: '2023-12-05',
  place_of_birth: 'Thọ Xuân, Thanh Hóa',
  ethnicity: null,
  nationality: null,
  permanent_address: '',
  temporary_address: '',
  passport_number: '123456',
  passport_date: '2025-10-10',
  passport_place: '222a',
  cccd_number: '222a',
  cccd_date: '2025-10-10',
  cccd_place: '222a',
  note: '222a',
  created_at: '2023-12-02T10:39:55.365422',
  year_of_birth: '1995',
  father_name: 'Lê Văn An',
  father_yob: '1982',
  mother_name: 'Nguyễn Thị Hà',
  mother_yob: '1982',
  significant_other_name: null,
  significant_other_yob: null,
  profile_type: 2,
  status: 'pending',
  created_by: 41,
  created_by_user: {
    id: 45,
    username: 'stp.admin',
    email: 'stp.admin@gmail.com',
    phone_number: '0389303982',
    first_name: 'Admin',
    last_name: 'admin',
    avatar_url:
      'https://cdn.senvangdata.com/senvang/2022/12/16/screen-shot-20221207-at-094321.png',
    status: 'active',
    organization_id: 1,
  },
};

export const DETAIL_VERIFY_LLTP = {
  request_citizen_profile: {
    id: 123,
    full_name: 'Lê Văn A',
    other_name: 'Lê Văn A',
    gender: 'male',
    date_of_birth: '2023-12-05',
    place_of_birth: 'Thọ Xuân, Thanh Hóa',
    ethnicity: 'ethnicity',
    nationality: 'nationality',
    permanent_address: 'permanent_address',
    temporary_address: 'temporary_address',
    type_identification: 'cccd',
    passport_number: '123456',
    passport_date: '2025-10-10',
    passport_place: '222a',
    cccd_number: 'cccd_number',
    cccd_date: '2025-10-10',
    cccd_place: '222a',
    note: '222a',
    created_at: '2023-12-02T10:39:55.365422',
    year_of_birth: '1995',
    father_name: 'Lê Văn An',
    father_yob: '1982',
    mother_name: 'Nguyễn Thị Hà',
    mother_yob: '1982',
    significant_other_name: null,
    significant_other_yob: null,
    profile_type: 2,
    status: 'pending',
    created_by: 41,
    created_by_user: {
      id: 45,
      username: 'stp.admin',
      email: 'stp.admin@gmail.com',
      phone_number: '0389303982',
      first_name: 'Admin',
      last_name: 'admin',
      avatar_url:
        'https://cdn.senvangdata.com/senvang/2022/12/16/screen-shot-20221207-at-094321.png',
      status: 'active',
      organization_id: 1,
    },
  },
  request_organization: {
    id: 281,
    citizen_profile_request_id: 1,
    organization_id: 1,
    organization: {
      id: 1,
      name: 'stp',
      display_name: 'Sở Tư Pháp',
    },
    verified_by: 45,
    verified_by_user: {
      id: 45,
      username: 'stp.admin',
      email: 'stp.admin@gmail.com',
      phone_number: '0389303982',
      first_name: 'Admin',
      last_name: 'admin',
      avatar_url:
        'https://cdn.senvangdata.com/senvang/2022/12/16/screen-shot-20221207-at-094321.png',
      status: 'active',
      organization_id: 1,
    },
    approved_by: 45,
    approved_by_user: {
      id: 45,
      username: 'stp.admin',
      email: 'stp.admin@gmail.com',
      phone_number: '0389303982',
      first_name: 'Admin',
      last_name: 'admin',
      avatar_url:
        'https://cdn.senvangdata.com/senvang/2022/12/16/screen-shot-20221207-at-094321.png',
      status: 'active',
      organization_id: 1,
    },
    status: 'pending',
    due_date: '2023-12-07',
    created_at: '2023-12-02T10:39:55.365422',
    request_create_at: '2023-12-02T10:39:55.365422',
    reject_reason: null,
    note: null,
  },
  request_verdicts: [
    {
      id: 1,
      case_number: 'case_number',
      date_of_verdict: '2023-12-06',
      court: 'toa an tinh Hai Duong',
      raw_document_id: 44,
      notes: 'notes',
      created_at: '2023-12-06 01:48:28.249000',
      content:
        '{"code_case_number":"22A", "toi_danh_dieu_khoan_cua_blhs_duoc_ap_dung":"Đánh nhau","hinh_phat_chinh":"hinh_phat_chinh","hinh_phat_bo_sung":"hinh_phat_bo_sung","nghia_vu_dan_su":"nghia_vu_dan_su","an_phi":10000,"ghi_chu_hinh_phat_chinh":"ghi_chu_hinh_phat_chinh","thoi_gian_phat_tu":"18 tháng","thoi_diem_chap_hanh_hinh_phat_chinh":"10/10/2014"}',
      document_type_id: 2,
      document_type: {
        id: 20,
        name: 'qdthbahs',
        display_name: 'Quyết định thi hành bản án hình sự',
        group_type: 'relate_document',
        created_at: '2023-12-02T10:24:48.701534',
        updated_at: '2023-12-11T09:31:41.446399',
      },
      created_by: 45,
      created_by_user: {
        id: 45,
        username: 'stp.admin',
        email: 'stp.admin@gmail.com',
        phone_number: '0389303982',
        first_name: 'Admin',
        last_name: 'admin',
        avatar_url:
          'https://cdn.senvangdata.com/senvang/2022/12/16/screen-shot-20221207-at-094321.png',
        status: 'active',
        organization_id: 1,
      },
      raw_document_object: {
        id: 2,
        raw_document_id: 2,
        object: '{}',
        case_number: '22a',
        group_type: 'verdict',
        created_at: '2023-12-02T10:24:48.701534',
      },
    },
  ],
  request_relate_documents: [
    {
      id: 1,
      verdict_number: 'case_number',
      raw_document_id: 22,
      created_at: '2023-12-06 01:48:28.249000',
      content:
        '{"so_quyet_dinh":"so_quyet_dinh","ngay_thang_nam_ra_quyet_dinh":"10/10/2022"}',
      document_type_id: 2,
      document_type: {
        id: 20,
        name: 'qdthbahs',
        display_name: 'Quyết định thi hành bản án hình sự',
        group_type: 'relate_document',
        created_at: '2023-12-02T10:24:48.701534',
        updated_at: '2023-12-11T09:31:41.446399',
      },
      created_by: 45,
      created_by_user: {
        id: 45,
        username: 'stp.admin',
        email: 'stp.admin@gmail.com',
        phone_number: '0389303982',
        first_name: 'Admin',
        last_name: 'admin',
        avatar_url:
          'https://cdn.senvangdata.com/senvang/2022/12/16/screen-shot-20221207-at-094321.png',
        status: 'active',
        organization_id: 1,
      },
      raw_document_object: {
        id: 2,
        raw_document_id: 2,
        object: '{}',
        case_number: '22a',
        group_type: 'verdict',
      },
    },
  ],
  prohibit_positions_documents: [
    {
      id: 1,
      raw_document_id: 22,
      created_at: '2023-12-06 01:48:28.249000',
      content:
        '{"so_quyet_dinh":"so_quyet_dinh","ngay_thang_nam_ra_quyet_dinh":"10/10/2022"}',
      document_type_id: 2,
      document_type: {
        id: 20,
        name: 'qdthbahs',
        display_name: 'Quyết định thi hành bản án hình sự',
        group_type: 'relate_document',
        created_at: '2023-12-02T10:24:48.701534',
        updated_at: '2023-12-11T09:31:41.446399',
      },
      created_by: 45,
      created_by_user: {
        id: 45,
        username: 'stp.admin',
        email: 'stp.admin@gmail.com',
        phone_number: '0389303982',
        first_name: 'Admin',
        last_name: 'admin',
        avatar_url:
          'https://cdn.senvangdata.com/senvang/2022/12/16/screen-shot-20221207-at-094321.png',
        status: 'active',
        organization_id: 1,
      },
      raw_document_object: {
        id: 2,
        raw_document_id: 2,
        object: '{}',
        case_number: '22a',
        group_type: 'verdict',
      },
    },
  ],
};

export const DETAIL_LLTP = {
  request_citizen_profile: {
    id: 1,
    full_name: 'Lê Văn A',
    other_name: 'Lê Văn A',
    gender: 'male',
    date_of_birth: '2023-12-05',
    place_of_birth: 'Thọ Xuân, Thanh Hóa',
    ethnicity: 'ethnicity',
    nationality: 'nationality',
    permanent_address: 'permanent_address',
    temporary_address: 'temporary_address',
    type_identification: 'cccd',
    passport_number: '123456',
    passport_date: '2025-10-10',
    passport_place: '222a',
    cccd_number: 'cccd_number',
    cccd_date: '2025-10-10',
    cccd_place: '222a',
    note: '222a',
    created_at: '2023-12-02T10:39:55.365422',
    year_of_birth: '1995',
    father_name: 'Lê Văn An',
    father_yob: '1982',
    mother_name: 'Nguyễn Thị Hà',
    mother_yob: '1982',
    significant_other_name: null,
    significant_other_yob: null,
    profile_type: 2,
    status: 'pending',
    created_by: 41,
    created_by_user: {
      id: 45,
      username: 'stp.admin',
      email: 'stp.admin@gmail.com',
      phone_number: '0389303982',
      first_name: 'Admin',
      last_name: 'admin',
      avatar_url:
        'https://cdn.senvangdata.com/senvang/2022/12/16/screen-shot-20221207-at-094321.png',
      status: 'active',
      organization_id: 1,
    },
  },
  request_organizations: [
    {
      id: 1,
      citizen_profile_request_id: 1,
      organization_id: 1,
      organization: {
        id: 1,
        name: 'stp',
        display_name: 'Sở Tư Pháp',
      },
      verified_by: 45,
      verified_by_user: {
        id: 45,
        username: 'stp.admin',
        email: 'stp.admin@gmail.com',
        phone_number: '0389303982',
        first_name: 'Admin',
        last_name: 'admin',
        avatar_url:
          'https://cdn.senvangdata.com/senvang/2022/12/16/screen-shot-20221207-at-094321.png',
        status: 'active',
        organization_id: 1,
      },
      approved_by: 45,
      approved_by_user: {
        id: 45,
        username: 'stp.admin',
        email: 'stp.admin@gmail.com',
        phone_number: '0389303982',
        first_name: 'Admin',
        last_name: 'admin',
        avatar_url:
          'https://cdn.senvangdata.com/senvang/2022/12/16/screen-shot-20221207-at-094321.png',
        status: 'active',
        organization_id: 1,
      },
      status: 'pending',
      due_date: '2023-12-07',
      created_at: '2023-12-02T10:39:55.365422',
      request_create_at: '2023-12-02T10:39:55.365422',
      reject_reason: null,
      note: null,
    },
  ],
  request_verdicts: [
    {
      id: 1,
      case_number: 'case_number',
      date_of_verdict: '2023-12-06',
      court: 'toa an tinh Hai Duong',
      raw_document_id: 44,
      notes: 'notes',
      created_at: '2023-12-06 01:48:28.249000',
      content:
        '{"code_case_number":"22A", "toi_danh_dieu_khoan_cua_blhs_duoc_ap_dung":"Đánh nhau","hinh_phat_chinh":"hinh_phat_chinh","hinh_phat_bo_sung":"hinh_phat_bo_sung","nghia_vu_dan_su":"nghia_vu_dan_su","an_phi":10000,"ghi_chu_hinh_phat_chinh":"ghi_chu_hinh_phat_chinh","thoi_gian_phat_tu":"18 tháng","thoi_diem_chap_hanh_hinh_phat_chinh":"10/10/2014"}',
      document_type_id: 2,
      document_type: {
        id: 20,
        name: 'qdthbahs',
        display_name: 'Quyết định thi hành bản án hình sự',
        group_type: 'relate_document',
        created_at: '2023-12-02T10:24:48.701534',
        updated_at: '2023-12-11T09:31:41.446399',
      },
      created_by: 45,
      created_by_user: {
        id: 45,
        username: 'stp.admin',
        email: 'stp.admin@gmail.com',
        phone_number: '0389303982',
        first_name: 'Admin',
        last_name: 'admin',
        avatar_url:
          'https://cdn.senvangdata.com/senvang/2022/12/16/screen-shot-20221207-at-094321.png',
        status: 'active',
        organization_id: 1,
      },
      raw_document_object: {
        id: 2,
        raw_document_id: 2,
        object: '{}',
        case_number: '22a',
        group_type: 'verdict',
        created_at: '2023-12-02T10:24:48.701534',
      },
    },
  ],
  request_relate_documents: [
    {
      id: 1,
      verdict_number: 'case_number',
      raw_document_id: 22,
      created_at: '2023-12-06 01:48:28.249000',
      content:
        '{"so_quyet_dinh":"so_quyet_dinh","ngay_thang_nam_ra_quyet_dinh":"10/10/2022"}',
      document_type_id: 2,
      document_type: {
        id: 20,
        name: 'qdthbahs',
        display_name: 'Quyết định thi hành bản án hình sự',
        group_type: 'relate_document',
        created_at: '2023-12-02T10:24:48.701534',
        updated_at: '2023-12-11T09:31:41.446399',
      },
      created_by: 45,
      created_by_user: {
        id: 45,
        username: 'stp.admin',
        email: 'stp.admin@gmail.com',
        phone_number: '0389303982',
        first_name: 'Admin',
        last_name: 'admin',
        avatar_url:
          'https://cdn.senvangdata.com/senvang/2022/12/16/screen-shot-20221207-at-094321.png',
        status: 'active',
        organization_id: 1,
      },
      raw_document_object: {
        id: 2,
        raw_document_id: 2,
        object: '{}',
        case_number: '22a',
        group_type: 'verdict',
      },
    },
  ],
  prohibit_positions_documents: [
    {
      id: 1,
      raw_document_id: 22,
      created_at: '2023-12-06 01:48:28.249000',
      content:
        '{"so_quyet_dinh":"so_quyet_dinh","ngay_thang_nam_ra_quyet_dinh":"10/10/2022"}',
      document_type_id: 2,
      document_type: {
        id: 20,
        name: 'qdthbahs',
        display_name: 'Quyết định thi hành bản án hình sự',
        group_type: 'relate_document',
        created_at: '2023-12-02T10:24:48.701534',
        updated_at: '2023-12-11T09:31:41.446399',
      },
      created_by: 45,
      created_by_user: {
        id: 45,
        username: 'stp.admin',
        email: 'stp.admin@gmail.com',
        phone_number: '0389303982',
        first_name: 'Admin',
        last_name: 'admin',
        avatar_url:
          'https://cdn.senvangdata.com/senvang/2022/12/16/screen-shot-20221207-at-094321.png',
        status: 'active',
        organization_id: 1,
      },
      raw_document_object: {
        id: 2,
        raw_document_id: 2,
        object: '{}',
        case_number: '22a',
        group_type: 'verdict',
      },
    },
  ],
};

export const COMMENTS = [
  {
    id: 0,
    user_id: 0,
    user: {
      id: 45,
      username: 'stp.admin',
      email: 'stp.admin@gmail.com',
      phone_number: '0389303982',
      first_name: 'Admin',
      last_name: 'admin',
      avatar_url:
        'https://cdn.senvangdata.com/senvang/2022/12/16/screen-shot-20221207-at-094321.png',
      status: 'active',
      organization_id: 1,
    },
    content: 'noi dung phan hoi',
    created_at: '2023-12-23T08:11:24.184Z',
    updated_at: '2023-12-23T08:11:24.184Z',
    citizen_profile_request_organization_id: 0,
    citizen_profile_request_organization: {
      id: 1,
      citizen_profile_request_id: 1,
      organization_id: 1,
      organization: {
        id: 1,
        name: 'stp',
        display_name: 'Sở Tư Pháp',
      },
      status: 'pending',
      due_date: '2023-12-07',
      created_at: '2023-12-02T10:39:55.365422',
      request_create_at: '2023-12-02T10:39:55.365422',
      reject_reason: null,
      note: null,
    },
  },
];

export const DETAIL_RAW_DOCUMENT = {
  id: 39,
  link: 'https://cdn.noron.vn/2023/12/13/adbfa0ba-c3db-46df-b2f0-086b29db1678-1702457142.PDF',
  document_template: {
    item_permissions: [],
    id: 11,
    config_template:
      '[{"label":"Số giấy chứng nhận","key-select":"other","key":"so_giay_chung_nhan","required":true,"type":"text"},{"label":"Ngày tháng năm cấp giấy chứng nhận","key-select":"orther","key":"ntncgcn","required":true,"type":"text"},{"label":"Cơ quan chứng nhận","key-select":"orther","key":"cqcn","required":true,"type":"text_area"},{"label":"Trụ sở","key-select":"other","key":"tru_so","type":"text_area"},{"label":"Ghi chú (phường, xã)","key-select":"other","key":"ghi_chu_(phuong,_xa)","type":"text_area"},{"label":"Án phạt đã chấp hành xong","key-select":"other","key":"an_phat_da_chap_hanh_xong","type":"text"},{"label":"Về nơi cư trú tại","key-select":"other","key":"ve_noi_cu_tru_tai","type":"text_area"},{"label":"Hình phạt bổ xung tiếp tục phải chấp hành","key-select":"other","key":"hinh_phat_bo_xung_tiep_tuc_phai_chap_hanh","type":"text_area"},{"label":"Ngày chấp hành xong án phạt","key-select":"other","key":"ngay_chap_hanh_xong_an_phat","type":"text"},{"label":"Ghi chú","key-select":"other","key":"ghi_chu","type":"text_area"},{"label":"Ngày cập nhật","key-select":"other","key":"ngay_cap_nhat","type":"text"},{"label":"Số bản án","key-select":"case_number","type":"text","key":"so_ban_an"}]',
    object_template: '[]',
    organization: {
      id: 9,
      name: 'VKS',
      display_name: 'Viện Kiểm Sát',
      created_at: '2023-12-20T11:02:30.039952',
      updated_at: '2023-12-20T11:02:30.039957',
    },
    document_type: {
      id: 22,
      name: 'gcndchxapt',
      display_name: 'Giấy chứng nhận đã chấp hành xong án phạt tù',
      group_type: 'relate_document',
      created_at: '2023-12-02T11:20:42.984918',
      updated_at: '2023-12-11T09:31:25.168677',
    },
    name: 'Giấy chứng nhận đã chấp hành xong án phạt tù',
    created_at: '2023-12-02T11:32:30.322741',
    updated_at: '2023-12-18T10:17:48.546164',
  },
  created_user: {
    id: 44,
    username: 'admin2',
    email: 'a.5695@gmail.com',
    phone_number: '0389303981',
    first_name: 'Super',
    last_name: 'Admin',
    avatar_url:
      'https://cdn.noron.vn/2023/12/14/598eb268-adb1-4451-96ea-8122f1a0e8f2-1702539527.jpg',
    status: 'active',
    organization_id: 1,
  },
  state: 'ocr_processing',
  created_at: '2023-12-13T15:45:47.770324',
  updated_at: '2023-12-13T15:45:47.770329',
  raw_text: 'null',
  document: {
    id: 1,
    raw_document_id: 22,
    created_at: '2023-12-06 01:48:28.249000',
    content:
      '{"so_quyet_dinh":"so_quyet_dinh","ngay_thang_nam_ra_quyet_dinh":"10/10/2022"}',
  },
  raw_document_objects: [
    {
      id: 2,
      raw_document_id: 2,
      object: '{}',
      case_number: '22a',
      group_type: 'verdict',
      created_at: '2023-12-02T10:24:48.701534',
    },
  ],
  ocr_result: 'null',
};

export const REQUEST_VERIFY_DOCUMENT = {
  document: {
    id: 1,
    created_at: '2023-12-06 01:48:28.249000',
    content:
      '{"so_quyet_dinh":"so_quyet_dinh","ngay_thang_nam_ra_quyet_dinh":"10/10/2022"}',
  },
  raw_document_objects: [
    {
      id: 2,
      object: '{}',
      case_number: '22a',
      group_type: 'verdict',
      created_at: '2023-12-02T10:24:48.701534',
    },
    {
      object: '{}',
      case_number: '22a',
      group_type: 'verdict',
      created_at: '2023-12-02T10:24:48.701534',
    },
  ],
  raw_document_object_ids_remove: [1],
};

export const NOTIS = [
  {
    id: 1,
    content: 'Bạn đang có một thông báo',
    created_at: '2023-12-02T10:24:48.701534',
    status: 'new', // new|viewed|read
    link: 'http://stp-web.internal.mhsolution.vn/',
    share_by_user: {
      id: 44,
      username: 'admin2',
      email: 'a.5695@gmail.com',
      phone_number: '0389303981',
      first_name: 'Super',
      last_name: 'Admin',
      avatar_url:
        'https://cdn.noron.vn/2023/12/14/598eb268-adb1-4451-96ea-8122f1a0e8f2-1702539527.jpg',
      status: 'active',
      organization_id: 1,
    },
  },
];

export const NOTI_SETTINGS = [
  {
    id: 1,
    type: 'lltp', //gồm 3 loại: hệ thống, cung cấp hồ sơ, lý lịch tư pháp
    name: 'Cấu hình',
    user_id: 44,
    status: 'enable', //enable|disable
  },
];
export const LOGS = [
  {
    id: 286,
    start_time: 1703564323371,
    request_body: 'null',
    ip_address: '10.56.9.11',
    user_id: 44,
    user_info_response: {
      first_name: 'Super',
      last_name: 'Admin',
      phone_number: '0389303981',
      email: 'a.5695@gmail.com',
      id: 44,
      avatar_url:
        'https://cdn.noron.vn/2023/12/14/598eb268-adb1-4451-96ea-8122f1a0e8f2-1702539527.jpg',
    },
    method: 'GET',
    code: 'access',
    path: '/api/v1/me',
    response_body:
      '{"item_permissions":["citizen-profile-request.view","document-type.search","citizen.search","raw-document.view","permission-role.add-list","prohibit-positions-document.add","role.delete","organization.view","citizen-profile-request-organization.un-receive","document-template.update","manage-api-receive.update","share-api-config.search","verdict.count","citizen.view","users.delete","raw-document.count","document-template.select","verdict.update","receive-data.search","manage-api-push.count","citizen-profile-request.delete","permission.user","prohibit-positions-document.view","raw-document.select","manage-api-push.update","raw-document.delete","permission.add","document-template.search-organization","organization.search","receive-data.deactive","setting-log.delete","receive-data.active","citizen.add","permission.add-list","users.select","role.view","user-action-log.search","push-data.update","receive-data.count","department-of-justice.update","push-data.view","citizen-profile-request.count","judicial-records.update","document-template.delete","citizen-profile-request.add","manage-api-receive.view","judicial-records.view","document-template.add","users.change-roles","manage-api-push.delete","department-of-justice.select","role.update","users.update","raw-document.add","judicial-records.unlocked","share-api-config.count","users.add","share-api-config.view","judicial-records.comment","permission-role.add","citizen-profile-request-document.update-document","prohibit-positions-document.update","citizen-profile-request-organization.reject","setting-log.count","document-template.view","citizen-profile-request-document.search","citizen.select","manage-api-receive.delete","permission-role.search","document-type.delete","role.select","organization.count","judicial-records.locked","manage-api-push.add","document-type.add","users.update-status","raw-document.search-organization","judicial-records.comment.search-organization","permission.get-by-page-name","prohibit-positions-document.count","permission.select","search.add","raw-document.detail","prohibit-positions-document.select","permission-role.delete","relate-document.select","citizen.count","manage-api-receive.count","citizen-profile-request.search","admin.push-data.count","citizen-profile-request-organization.verify","citizen.update","organization.update","judicial-records.comment.count","share-api-config.add","verdict.select","relate-document.update","setting-log.view","view.add","raw-document.update","document-template.search","setting-log.update","share-api-config.update","citizen-profile-request-organization.search","permission.update","permission-role.view","judicial-records.detail","verdict.search","judicial-records.comment.search","receive-data.view","receive-data.update","relate-document.count","department-of-justice.count","citizen-profile-request-organization.receive","organization.select","role.get-all","push-data.add","department-of-justice.view","role.add","admin.push-data.delete","citizen-profile-request-document.view","citizen-profile-request-document.add","citizen-profile-request-organization.approve","permission.delete","document-type.view","citizen-profile-request-document.delete","relate-document.add","judicial-records.comment.insert-organization","verdict.view","relate-document.search","manage-api-receive.search","push-data.search","department-of-justice.search","document-type.select","push-data.deactive","push-data.delete","raw-document.search-organization.abc","judicial-records.draft-save","permission.get-all","users.view","manage-api-receive.add","citizen-profile-request-document.change-roles","document-type.count","judicial-records.detail-organization","permission.count","document-type.update","prohibit-positions-document.search","department-of-justice.add","document-template.count","admin.push-data.search","permission.search","verdict.suggest-by-search","relate-document.view","organization.add","receive-data.delete","department-of-justice.get-all","user-action-log.export.excel","role.search","organization.delete","verdict.delete","relate-document.delete","judicial-records.comment.delete","citizen.delete","share-api-config.delete","verdict.add","raw-document.search","judicial-records.delete","push-data.active","users.search","judicial-records.add","setting-log.search","raw-document.approved","push-data.count","raw-document.verify","view.view","permission.view","role.count","role.setting","manage-api-push.view","manage-api-push.search","setting-log.add","receive-data.add","permission-role.update","admin.push-data","form-setting.view","department-of-justice.delete","citizen-profile-request.update","users.count","citizen-profile-request-document.update","department-of-justice.insert","prohibit-positions-document.delete","citizen-profile-request-organization.view"],"id":44,"username":"admin2","email":"a.5695@gmail.com","phone_number":"0389303981","first_name":"Super","last_name":"Admin","avatar_url":"https://cdn.noron.vn/2023/12/14/598eb268-adb1-4451-96ea-8122f1a0e8f2-1702539527.jpg","status":"active","roles":["ADMIN 1"],"organization_id":1}',
  },
];

export const PLATFORMS = [
  { code: 'district', name: 'Nền tảng kho dữ liệu dùng chung Quận/Huyện' },
  { code: 'department', name: 'Nền tảng kho dữ liệu dùng chung Sở/Ngành' },
  { code: 'province', name: 'Nền tảng kho dữ liệu dùng chung tỉnh' },
  { code: 'lgsp', name: 'Nền tảng LGSP' },
  { code: 'city', name: 'Nền tảng điều hành đô thị Thông minh' },
  { code: 'provincial_information_portal', name: 'Cổng thông tin tỉnh' },
  { code: 'other_systems_procuracy', name: 'Hệ thống khác tại Viện kiểm sát' },
  { code: 'other_systems_court', name: 'Hệ thống khác tại Tòa án' },
  {
    code: 'other_systems_execution_judgment',
    name: 'Hệ thống khác tại Thi hành án',
  },
  { code: 'other_systems_police', name: 'Hệ thống khác tại Công an' },
];

export const a = [
  {
    profile: '',
    sample_1: '',
    sample_2: '',
    status: '',
    created_at: '2023-12-02T10:39:55.365422',
    created_by: 41,
    created_by_user: {
      id: 45,
      username: 'stp.admin',
      email: 'stp.admin@gmail.com',
      phone_number: '0389303982',
      first_name: 'Admin',
      last_name: 'admin',
      avatar_url:
        'https://cdn.senvangdata.com/senvang/2022/12/16/screen-shot-20221207-at-094321.png',
      status: 'active',
      organization_id: 1,
    },
    citizen_profile: {
      id: 1,
      full_name: 'Lê Văn A',
      other_name: 'Lê Văn A',
      gender: 'male',
      date_of_birth: '2023-12-05',
      place_of_birth: 'Thọ Xuân, Thanh Hóa',
      ethnicity: null,
      nationality: null,
      permanent_address: '',
      temporary_address: '',
      passport_number: '123456',
      passport_date: '2025-10-10',
      passport_place: '222a',
      cccd_number: '222a',
      cccd_date: '2025-10-10',
      cccd_place: '222a',
      note: '222a',
      created_at: '2023-12-02T10:39:55.365422',
      year_of_birth: '1995',
      father_name: 'Lê Văn An',
      father_yob: '1982',
      mother_name: 'Nguyễn Thị Hà',
      mother_yob: '1982',
      significant_other_name: null,
      significant_other_yob: null,
      profile_type: 2,
      status: 'pending',
      created_by: 41,
      created_by_user: {
        id: 45,
        username: 'stp.admin',
        email: 'stp.admin@gmail.com',
        phone_number: '0389303982',
        first_name: 'Admin',
        last_name: 'admin',
        avatar_url:
          'https://cdn.senvangdata.com/senvang/2022/12/16/screen-shot-20221207-at-094321.png',
        status: 'active',
        organization_id: 1,
      },
    },
    verdicts: [
      {
        id: 1,
        case_number: '22a',
        date_of_verdict: '22a',
        court: 'toa an tinh Hai Duong',
        raw_document_id: 'toa an tinh Hai Duong',
        notes: '',
        created_at: '2023-12-06 01:48:28.249000',
        content: '{}',
        document_type_id: 2,
        document_type: {
          id: 20,
          name: 'qdthbahs',
          display_name: 'Quyết định thi hành bản án hình sự',
          group_type: 'relate_document',
          created_at: '2023-12-02T10:24:48.701534',
          updated_at: '2023-12-11T09:31:41.446399',
        },
        created_by: 45,
        created_by_user: {
          id: 45,
          username: 'stp.admin',
          email: 'stp.admin@gmail.com',
          phone_number: '0389303982',
          first_name: 'Admin',
          last_name: 'admin',
          avatar_url:
            'https://cdn.senvangdata.com/senvang/2022/12/16/screen-shot-20221207-at-094321.png',
          status: 'active',
          organization_id: 1,
        },
        raw_document_object: {
          id: 2,
          raw_document_id: 2,
          object: '{}',
          case_number: '22a',
          group_type: 'verdict',
        },
      },
    ],
    relate_documents: [
      {
        id: 1,
        verdict_number: '22a',
        raw_document_id: 22,
        created_at: '2023-12-06 01:48:28.249000',
        content: '{}',
        document_type_id: 2,
        document_type: {
          id: 20,
          name: 'qdthbahs',
          display_name: 'Quyết định thi hành bản án hình sự',
          group_type: 'relate_document',
          created_at: '2023-12-02T10:24:48.701534',
          updated_at: '2023-12-11T09:31:41.446399',
        },
        created_by: 45,
        created_by_user: {
          id: 45,
          username: 'stp.admin',
          email: 'stp.admin@gmail.com',
          phone_number: '0389303982',
          first_name: 'Admin',
          last_name: 'admin',
          avatar_url:
            'https://cdn.senvangdata.com/senvang/2022/12/16/screen-shot-20221207-at-094321.png',
          status: 'active',
          organization_id: 1,
        },
        raw_document_object: {
          id: 2,
          raw_document_id: 2,
          object: '{}',
          case_number: '22a',
          group_type: 'verdict',
        },
      },
    ],
    prohibit_positions_documents: [
      {
        id: 1,
        raw_document_id: 22,
        created_at: '2023-12-06 01:48:28.249000',
        content: '{}',
        document_type_id: 2,
        document_type: {
          id: 20,
          name: 'qdthbahs',
          display_name: 'Quyết định thi hành bản án hình sự',
          group_type: 'relate_document',
          created_at: '2023-12-02T10:24:48.701534',
          updated_at: '2023-12-11T09:31:41.446399',
        },
        created_by: 45,
        created_by_user: {
          id: 45,
          username: 'stp.admin',
          email: 'stp.admin@gmail.com',
          phone_number: '0389303982',
          first_name: 'Admin',
          last_name: 'admin',
          avatar_url:
            'https://cdn.senvangdata.com/senvang/2022/12/16/screen-shot-20221207-at-094321.png',
          status: 'active',
          organization_id: 1,
        },
        raw_document_object: {
          id: 2,
          raw_document_id: 2,
          object: '{}',
          case_number: '22a',
          group_type: 'verdict',
        },
      },
    ],
  },
];

export const NOTI_RES = [
  {
    id: 1,
    content: 'Bạn đang có một thông báo',
    created_at: '2023-12-22T10:24:48.701534',
    status: 'read', // new|viewed|read
    link: 'http://stp-web.internal.mhsolution.vn/',
    share_by_user: {
      id: 44,
      username: 'admin2',
      email: 'a.5695@gmail.com',
      phone_number: '0389303981',
      first_name: 'Super',
      last_name: 'Admin',
      avatar_url:
        'https://cdn.noron.vn/2023/12/14/598eb268-adb1-4451-96ea-8122f1a0e8f2-1702539527.jpg',
      status: 'active',
      organization_id: 1,
    },
  },

  {
    id: 2,
    content: 'Bạn đang có một thông báo',
    created_at: '2023-12-28T10:24:48.701534',
    status: 'viewed', // new|viewed|read
    link: 'http://stp-web.internal.mhsolution.vn/',
    share_by_user: {
      id: 44,
      username: 'admin2',
      email: 'a.5695@gmail.com',
      phone_number: '0389303981',
      first_name: 'Super',
      last_name: 'Admin',
      avatar_url:
        'https://cdn.noron.vn/2023/12/14/598eb268-adb1-4451-96ea-8122f1a0e8f2-1702539527.jpg',
      status: 'active',
      organization_id: 1,
    },
  },
  {
    id: 3,
    content: 'Bạn đang có một thông báo',
    created_at: '2023-12-02T10:24:48.701534',
    status: 'read', // new|viewed|read
    link: 'http://stp-web.internal.mhsolution.vn/',
    share_by_user: {
      id: 44,
      username: 'admin2',
      email: 'a.5695@gmail.com',
      phone_number: '0389303981',
      first_name: 'Super',
      last_name: 'Admin',
      avatar_url:
        'https://cdn.noron.vn/2023/12/14/598eb268-adb1-4451-96ea-8122f1a0e8f2-1702539527.jpg',
      status: 'active',
      organization_id: 1,
    },
  },
];

export const dataUpdateLLTP = {
  add_verdicts: [
    {
      id: 2, // id verdict,
      raw_document_id: 2, // raw_document_id,
      raw_document_object_id: 2, // raw_document_object_id,
    },
  ],
  remove_verdicts: [
    {
      id: 2, // id verdict,
      raw_document_id: 2, // raw_document_id,
      raw_document_object_id: 2, // raw_document_object_id,
    },
  ],
  add_relate_documents: [
    {
      id: 2, // id verdict,
      raw_document_id: 2, // raw_document_id,
      raw_document_object_id: 2, // raw_document_object_id,
    },
  ],
  remove_relate_documents: [
    {
      id: 2, // id verdict,
      raw_document_id: 2, // raw_document_id,
      raw_document_object_id: 2, // raw_document_object_id,
    },
  ],
  add_prohibit_positions_documents: [
    {
      id: 2, // id verdict,
      raw_document_id: 2, // raw_document_id,
      raw_document_object_id: 2, // raw_document_object_id,
    },
  ],
  remove_prohibit_positions_documents: [
    {
      id: 2, // id verdict,
      raw_document_id: 2, // raw_document_id,
      raw_document_object_id: 2, // raw_document_object_id,
    },
  ],
};

export const LIST_QA = [
  {
    id: 1,
    name: 'Fured seems search us level we pee work thought cta?',
    content:
      "Join now job low-hanging we've and. Issues synergize just blue guys when happenings algorithm pivot moving. Window muted idea company banner feed site power cost. Across manager meat asserts yet crystallize. Going new right scraps optimize what's functional would believe. \n" +
      'Later whatever plan regroup take stands finance launch low. Incentivization cross-pollination need people developing stronger light social if speed. Cadence power break team third tomorrow we. Solutions version emails wiggle make when bed. Both but just leverage at silently.\n' +
      "Highlights stop 30,000ft rundown driving pole hammer it. Sorry bake synchronise talk call performance fruit. Deck comms savvy algorithm no-brainer gave offline. Unlock caught strategic hanging stakeholders before of agile. Quarter cross-pollination blue or food keep it's procrastinating. Turn hit revision next lean.",
    category_code: 'Q',
  },
  {
    id: 2,
    name: 'Fured seems search us level we pee work thought cta?',
    content:
      "Join now job low-hanging we've and. Issues synergize just blue guys when happenings algorithm pivot moving. Window muted idea company banner feed site power cost. Across manager meat asserts yet crystallize. Going new right scraps optimize what's functional would believe. \n" +
      'Later whatever plan regroup take stands finance launch low. Incentivization cross-pollination need people developing stronger light social if speed. Cadence power break team third tomorrow we. Solutions version emails wiggle make when bed. Both but just leverage at silently.\n' +
      "Highlights stop 30,000ft rundown driving pole hammer it. Sorry bake synchronise talk call performance fruit. Deck comms savvy algorithm no-brainer gave offline. Unlock caught strategic hanging stakeholders before of agile. Quarter cross-pollination blue or food keep it's procrastinating. Turn hit revision next lean.",
    category_code: 'Q',
  },
  {
    id: 3,
    name: 'Fured seems search us level we pee work thought cta?',
    content:
      "Join now job low-hanging we've and. Issues synergize just blue guys when happenings algorithm pivot moving. Window muted idea company banner feed site power cost. Across manager meat asserts yet crystallize. Going new right scraps optimize what's functional would believe. \n" +
      'Later whatever plan regroup take stands finance launch low. Incentivization cross-pollination need people developing stronger light social if speed. Cadence power break team third tomorrow we. Solutions version emails wiggle make when bed. Both but just leverage at silently.\n' +
      "Highlights stop 30,000ft rundown driving pole hammer it. Sorry bake synchronise talk call performance fruit. Deck comms savvy algorithm no-brainer gave offline. Unlock caught strategic hanging stakeholders before of agile. Quarter cross-pollination blue or food keep it's procrastinating. Turn hit revision next lean.",
    category_code: 'Q',
  },
];

export const LIST_CONFIG = [
  {
    id: 1,
    name: 'Họ và tên',
    config: '${full_name}',
  },
  {
    id: 2,
    name: 'Tuổi',
    config: '${age}',
  },
  {
    id: 3,
    name: 'Địa chỉ',
    config: '${address}',
  },
  {
    id: 4,
    name: 'Giới tính',
    config: '${gender}',
  },
  {
    id: 5,
    name: 'Ngày sinh',
    config: '${date}',
  },
];

export const LIST_INFO_CONFIG_INSTRUCTIONS = [
  {
    colC1: 'C1',
    colC2: 'C2',
    colC3: 'C3',
    colCDots: '...',
    colCn: 'Cn',
  },
  {
    key: '1',
    serial: 'R1',
    colH: 'H1',
    colC1: 'C1R1H1',
    colC2: 'C2R1H1',
    colC3: 'C3R1H1',
    colCn: 'CnR1H1',
  },
  {
    key: '2',
    serial: 'R1',
    colH: 'H2',
    colC1: 'C1R1H2',
    colC2: 'C2R1H2',
    colC3: 'C3R1H2',
    colCn: 'CnR1H2',
  },
  {
    key: '3',
    serial: 'R1',
    colH: 'H3',
    colC1: 'C1R1H3',
    colC2: 'C2R1H3',
    colC3: 'C3R1H3',
    colCn: 'CnR1H3',
  },
  {
    key: '4',
    serial: 'R1',
    colH: '...',
    colC1: '...',
    colC2: '...',
    colC3: '...',
    colCn: '...',
  },
  {
    key: '5',
    serial: 'R1',
    colH: 'Hn',
    colC1: 'C1R1Hn',
    colC2: 'C2R1Hn',
    colC3: 'C3R1Hn',
    colCn: 'CnR1Hn',
  },
  {
    key: '6',
    serial: 'R2',
    colH: 'H1',
    colC1: 'C1R2H1',
    colC2: 'C2R2H1',
    colC3: 'C3R2H1',
    colCn: 'CnR2H1',
  },
  {
    key: '7',
    serial: 'R2',
    colH: 'H2',
    colC1: 'C1R2H2',
    colC2: 'C2R2H2',
    colC3: 'C3R2H2',
    colCn: 'CnR2H2',
  },
  {
    key: '8',
    serial: 'R2',
    colH: 'H3',
    colC1: 'C1R2H3',
    colC2: 'C2R2H3',
    colC3: 'C3R2H3',
    colCn: 'CnR2H3',
  },
  {
    key: '9',
    serial: 'R2',
    colH: '...',
    colC1: '...',
    colC2: '...',
    colC3: '...',
    colCn: '...',
  },
  {
    key: '10',
    serial: 'R2',
    colH: 'Hn',
    colC1: 'C1R2Hn',
    colC2: 'C2R2Hn',
    colC3: 'C3R2Hn',
    colCn: 'CnR2Hn',
  },
  {
    key: '11',
    serial: 'R3',
    colH: 'H1',
    colC1: 'C1R3H1',
    colC2: 'C2R3H1',
    colC3: 'C3R3H1',
    colCn: 'CnR3H1',
  },
  {
    key: '12',
    serial: 'R3',
    colH: 'H2',
    colC1: 'C1R3H2',
    colC2: 'C2R3H2',
    colC3: 'C3R3H2',
    colCn: 'CnR3H2',
  },
  {
    key: '13',
    serial: 'R3',
    colH: 'H3',
    colC1: 'C1R3H3',
    colC2: 'C2R3H3',
    colC3: 'C3R3H3',
    colCn: 'CnR3H3',
  },
  {
    key: '14',
    serial: 'R3',
    colH: '...',
    colC1: '...',
    colC2: '...',
    colC3: '...',
    colCn: '...',
  },
  {
    key: '15',
    serial: 'R3',
    colH: 'Hn',
    colC1: 'C1R3Hn',
    colC2: 'C2R3Hn',
    colC3: 'C3R3Hn',
    colCn: 'CnR3Hn',
  },
  {
    key: '16',
    serial: '...',
    colH: '...',
    colC1: '...',
    colC2: '...',
    colC3: '...',
    colCn: '...',
  },
  {
    key: '17',
    serial: 'Rn',
    colH: 'H1',
    colC1: 'C1RnH1',
    colC2: 'C2RnH1',
    colC3: 'C3RnH1',
    colCn: 'CnRnH1',
  },
  {
    key: '18',
    serial: 'Rn',
    colH: 'H2',
    colC1: 'C1RnH2',
    colC2: 'C2RnH2',
    colC3: 'C3RnH2',
    colCn: 'CnRnH2',
  },
  {
    key: '19',
    serial: 'Rn',
    colH: 'H3',
    colC1: 'C1RnH3',
    colC2: 'C2RnH3',
    colC3: 'C3RnH3',
    colCn: 'CnRnH3',
  },
  {
    key: '20',
    serial: 'Rn',
    colH: '...',
    colC1: '...',
    colC2: '...',
    colC3: '...',
    colCn: '...',
  },
  {
    key: '21',
    serial: 'Rn',
    colH: 'Hn',
    colC1: 'C1RnHn',
    colC2: 'C2RnHn',
    colC3: 'C3RnHn',
    colCn: 'CnRnHn',
  },
];
