export const FORM_TYPES = {
  ADD: 'add',
  UPDATE: 'update',
  COPY: 'copy',
  INFO: 'info',
  DRAFT: 'draft',
  ADD_ORGANIZATION: 'add_organization',
  DETAIL: 'detail',
  PERMISSION: 'permission',
  REFUSE_AMBASSADOR: 'refuse_ambassador',
  REGISTER_AMBASSADOR: 'register_ambassador',
  CHANGE_CONTENT_PROJECT: 'change_content_project',
  INSTALL: ' install',
  ADD_DESTINATION: 'add-destination',
  ADD_VIDEO: 'add_video',
  GRANTING_ACCESS: 'granting_access',
  RETRIEVE_API: 'retrieve_api',
  UPDATE_ADD_DATA: 'update_add_data',
  CREATE_ADD_DATA: 'create_add_data',
};

export const FORM_CONFIG = [
  {
    type: FORM_TYPES.ADD,
    title: 'form.formTitleAdd',
    buttonText: 'form.buttonAdd',
    successMessage: 'form.addSuccessMessage',
    successDraftMessage: 'form.draftSuccessMessage',
  },
  {
    type: FORM_TYPES.ADD_VIDEO,
    title: 'form.formTitleAddVideo',
  },
  {
    type: FORM_TYPES.GRANTING_ACCESS,
    title: 'form.formTitleGrantingAccess',
  },

  {
    type: FORM_TYPES.ADD_ORGANIZATION,
    title: 'form.formTitleAdd',
    buttonText: 'form.buttonCreate',
    successMessage: 'form.addSuccessMessage',
    successDraftMessage: 'form.draftSuccessMessage',
  },
  {
    type: FORM_TYPES.DETAIL,
    title: 'form.formTitleDetail',
    buttonText: 'form.buttonDetail',
    successMessage: 'form.addSuccessMessage',
    successDraftMessage: 'form.draftSuccessMessage',
  },
  {
    type: FORM_TYPES.ADD_ORGANIZATION,
    title: 'form.formTitleAdd',
    buttonText: 'form.buttonSave',
    successMessage: 'form.addSuccessMessage',
  },
  {
    type: FORM_TYPES.PERMISSION,
    title: 'form.formTitleAdd',
    buttonText: 'form.buttonAdd',
    successMessage: 'form.addSuccessMessage',
  },
  {
    type: FORM_TYPES.INSTALL,
    title: 'form.formTitleInstall',
    buttonText: 'form.buttonAdd',
    successMessage: 'form.addSuccessMessage',
    successDraftMessage: 'form.draftSuccessMessage',
  },
  {
    type: FORM_TYPES.ADD_ORGANIZATION,
    title: 'form.formTitleAdd',
    buttonText: 'form.buttonCreate',
    successMessage: 'form.addSuccessMessage',
    successDraftMessage: 'form.draftSuccessMessage',
  },
  {
    type: FORM_TYPES.DETAIL,
    title: 'form.formTitleDetail',
    buttonText: 'form.buttonDetail',
    successMessage: 'form.addSuccessMessage',
    successDraftMessage: 'form.draftSuccessMessage',
  },
  {
    type: FORM_TYPES.ADD_ORGANIZATION,
    title: 'form.formTitleAdd',
    buttonText: 'form.buttonSave',
    successMessage: 'form.addSuccessMessage',
  },
  {
    type: FORM_TYPES.PERMISSION,
    title: 'form.formTitleAdd',
    buttonText: 'form.buttonAdd',
    successMessage: 'form.addSuccessMessage',
  },
  {
    type: FORM_TYPES.UPDATE,
    title: 'form.formTitleUpdate',
    buttonText: 'form.buttonUpdate',
    successMessage: 'form.updateSuccessMessage',
  },
  {
    type: FORM_TYPES.UPDATE_ADD_DATA,
    title: 'form.formTitleUpdate',
    buttonText: 'form.formTitleUpdate',
    successMessage: 'form.createRequestUpdateSuccess',
  },
  {
    type: FORM_TYPES.CREATE_ADD_DATA,
    title: 'table.action.add',
    buttonText: 'table.action.add',
    successMessage: 'form.createRequestCreateSuccess',
  },
  {
    type: FORM_TYPES.SEARCH,
    title: 'form.formTitleSearch',
    buttonText: 'form.buttonSearch',
  },
  {
    type: FORM_TYPES.ADD_DESTINATION,
    title: 'form.formTitleAddDestination',
    buttonText: 'form.buttonAdd',
    successMessage: 'form.addSuccessMessage',
  },
  {
    type: FORM_TYPES.COPY,
    title: 'form.formTitleCopy',
    buttonText: 'form.buttonCopy',
    successMessage: 'form.CopySuccessMessage',
  },
  {
    type: FORM_TYPES.INFO,
    title: 'form.formTitleInfo',
    buttonText: '',
    successMessage: '',
  },
  {
    type: FORM_TYPES.REGISTER_AMBASSADOR,
    title: 'ambassador.formRegister',
    configCancelText: 'dialog.button.close',
    successMessage: '',
  },
  {
    type: FORM_TYPES.REFUSE_AMBASSADOR,
    title: 'ambassador.formTitle.refuse',
    buttonText: 'ambassador.buttonText.refuse',
    successMessage: 'ambassador.successMessage.refuse',
  },
  {
    type: FORM_TYPES.CHANGE_CONTENT_PROJECT,
    title: 'project.change.content.title',
    buttonText: 'project.change.content.buttonText',
    successMessage: 'project.change.content.success',
  },
  {
    type: FORM_TYPES.DRAFT,
  },
  {
    type: FORM_TYPES.RETRIEVE_API,
    successMessage: 'form.formTitleRetrieveDataApi',
  },
];
