export const TABLE_ACTION = {
  DELETE: 'delete',
  PAUSE: 'pause',
  RUNNING: 'running',
  STOP: 'stop',
  HIDE: 'hide',
  SHOW: 'show',
  REFUSE: 'refuse',
  LOCK: 'lock',
  UNLOCK: 'unlock',
  REASON_REFUSE: 'reasonRefuse',
  CHANGE_STATUS_INTERVIEW: 'changeStatusInterview',
  REJECT: 'reject',
  UPGRADE: 'upgrade',
  APPROVE: 'approve',
  APPEAL: 'appeal',
  REASON_APPEAL: 'reasonAppeal',
  REASON_REPORT: 'reasonReport',
  ACTIVATE: 'activate',
  DEACTIVATE: 'deactivate',
  CREATE: 'create',
  UPDATE: 'update',
  AUTO_SYNC: 'autoSync',
  HAND_SYNC: 'handSync',
  DELETE_MULTI: 'deleteMulti',
  SYNC: 'sync',
  PRINT: 'print',
};
